# .github/release.yml

changelog:
  exclude:
    labels:
      - maintenance
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Exciting New Features 🎉
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bugfix
        - bug
    - title: Dependency Updates
      labels:
        - dependencies
    - title: Documentation
      labels:
        - docs
    - title: And more...
      labels:
        - "*"
