[tools]
1password = '2.30.3'
# Should match go.mod
go = "1.24"
"go:github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs" = "0.22.0"
"go:github.com/BurntSushi/toml/cmd/tomlv" = "1.5.0"
golangci-lint = "2.3.0"
goreleaser = "2.11.2"
gotestsum = "1.12.3"
pre-commit = "4.2.0"
terraform = "1.12.2"

[settings]
# Enable experimental mode to support installing
# specific go binaries by URL, for those that are
# not yet available in the mise registry..
experimental = true
