[tools]
1password = "2.34.0"
# Should match go.mod
go = "1.26"
"go:github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs" = "0.25.0"
"go:github.com/BurntSushi/toml/cmd/tomlv" = "1.6.0"
golangci-lint = "2.12.2"
goreleaser = "2.16.0"
gotestsum = "1.13.0"
pre-commit = "4.6.0"
terraform = "1.15.5"

[vars]
helper_tests_arg='specify tests as an argument: mise run <task> "TestAccResource_flow"'

[tasks.default]
description = "List available tasks"
alias = "h"
run = [
  "mise tasks",
  "printf '\nRun `mise task info <task>` for more information on each task.'"
]
quiet = true

[tasks.build]
description = "Build the provider binary"
alias = "b"
run = [
  "mkdir -p .build/",
  "go build -o .build/terraform-provider-prefect",
]
run_windows = [
  "mkdir -p .build",
  "go build -o .build\\terraform-provider-prefect",
] # this will typically only be relevant in CI, where it otherwise reports "incorrect syntax"
sources = ["internal/**/*.go", "tools/**/*.go", "main.go", "go.mod", "go.sum", ".mise.toml"]
outputs = [".build/terraform-provider-prefect"]

[tasks.clean]
alias = "c"
description = "Clean up built artifacts"
run = "rm -vrf .build/"

[tasks.dev-clean]
alias = "dc"
description = "Clean up dev artifacts"
run = "rm -vrf dev/"

[tasks.lint]
alias = "l"
description = "Run static code analysis"
run = "golangci-lint run"

[tasks.test]
alias = "t"
description = "Run automated unit tests ({{vars.helper_tests_arg}})"
usage = 'arg "[tests]" default="" env="TESTS"'
run = 'tests="${usage_tests?}"; gotestsum --max-fails=50 ./... -run "${tests#TESTS=}"'
run_windows = 'gotestsum --max-fails=50 ./...'

[tasks.testacc]
alias = "ta"
description = "Run acceptance tests against real infrastructure ({{vars.helper_tests_arg}})"
usage = 'arg "[tests]" default="" env="TESTS"'
run = 'tests="${usage_tests?}"; TF_ACC=1 mise run test "${tests#TESTS=}"'

[tasks.testacc-dev]
alias = "tad"
description = "Run automated acceptance tests from a local machine ({{vars.helper_tests_arg}})"
usage = '''
arg "[tests]" default="" env="TESTS"
arg "[log_level]" default="" env="LOG_LEVEL"
arg "[sweep]" default="" env="SWEEP"
'''
run = 'tests="${usage_tests?}"; log_level="${usage_log_level?}"; sweep="${usage_sweep?}"; scripts/testacc-dev "${tests#TESTS=}" "${log_level#LOG_LEVEL=}" "${sweep#SWEEP=}"'

[tasks.testacc-dev-user]
alias = "tadu"
description = "Run automated acceptance tests for user-related resources from a local machine"
file = 'scripts/testacc-dev-user'

[tasks.testacc-cm]
alias = "tac"
description = "Run automated acceptance tests against a Customer-Managed instance from a local machine ({{vars.helper_tests_arg}})"
usage = '''
arg "[tests]" default="" env="TESTS"
arg "[log_level]" default="" env="LOG_LEVEL"
arg "[sweep]" default="" env="SWEEP"
'''
run = 'tests="${usage_tests?}"; log_level="${usage_log_level?}"; sweep="${usage_sweep?}"; scripts/testacc-cm "${tests#TESTS=}" "${log_level#LOG_LEVEL=}" "${sweep#SWEEP=}"'

[tasks.testacc-oss]
alias = "tao"
description = "Run automated acceptance tests for Prefect OSS"
usage = 'arg "[tests]" default="" env="TESTS"'
run = [
  "docker compose up -d",
  'tests="${usage_tests?}"; ./scripts/testacc-oss "${tests#TESTS=}"',
  "docker compose down"
]

[tasks.testacc-sweepers]
alias = "tas"
description = "Run automated acceptance test sweepers"
run = "go test ./internal/sweep -v -sweep=all"

[tasks.docs]
alias = "d"
description = "Build Terraform documentation"
run = [
  "rm -rf docs/",
  "mkdir docs/",
  "tfplugindocs generate --rendered-provider-name Prefect --provider-name prefect",
]

[tasks.dev-new]
alias = "dn"
description = "Creates a new dev testfile"
usage = '''
arg "<resource>"
arg "[resourcename]" default=""
'''
run = 'sh create-dev-testfile.sh "${usage_resource?}" "${usage_resourcename?}"'

[settings]
# Enable experimental mode to support installing
# specific go binaries by URL, for those that are
# not yet available in the mise registry..
experimental = true
