[tools]
golang = '1.21.10'
golangci-lint = '1.61.0'
goreleaser = '1.26.2'
gotestsum = '1.12.0'
pre-commit = '3.7.1'
terraform = '1.9.8'

# tomlv does not currently have an entry in the registry.
# For now, install with `go`:
# go get github.com/BurntSushi/toml/cmd/tomlv
