version: "3.8"

services:
  testacc:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PREFECT__CLOUD__API_KEY
      - TF_ACC=1
    command: ["go", "test", "-v", "./..."]
