package client

import (
	"net/http"

	"github.com/google/uuid"
)

type Client struct {
	hc           *http.Client
	endpoint     string
	endpointHost string

	apiKey       string
	basicAuthKey string

	// csrfClientToken is a UUID generated by the client and sent via the Prefect-Csrf-Client header.
	csrfClientToken string
	// csrfToken is the token obtained from the server and sent via the Prefect-Csrf-Token header.
	csrfToken string

	// customHeaders are user-defined HTTP headers to include in all API requests.
	customHeaders map[string]string

	defaultAccountID   uuid.UUID
	defaultWorkspaceID uuid.UUID
}

type Option func(c *Client) error
