#!/usr/bin/env bash
set -e

# This script runs the acceptance tests from a local machine
# against a Customer-Managed test instance.
#
# It collects the required environment variables from 1Password
# using its CLI: https://developer.1password.com/docs/cli/secrets-scripts
#
# To run specific tests, add the test name as the first argument:
#   ./scripts/testacc-cm TestAccResource_deployment
#
# To adjust the log level, specify it as the second argument:
#   ./scripts/testacc-cm TestAccResource_deployment DEBUG
#
# Log levels are listed here:
#   https://developer.hashicorp.com/terraform/internals/debugging

vault_entry='op://Platform/terraform-provider-acceptance-tests-cm'

tests=${1:-""}
log_level=${2:-"INFO"}
sweep=${3:-""}

run_arg=""
if [ "${sweep}" != "" ]; then
  # If sweep is set to anything, only run the sweepers and skip the acceptance tests.
  # This only runs on the 'resources' and 'datasources' packages, as those contain
  # acceptance tests where sweepers apply.
  #
  # The '-v' flag ensures that 'fmt.Printf' statements are visible.
  echo "sweeping..."
  run_arg="go test ./internal/sweep -v -sweep=all"
elif [ "${tests}" != "" ]; then
  echo "specific test(s) configured: ${tests}"
  run_arg="gotestsum --max-fails=50 ./... -count=1 -v -run ^${tests}$"
else
  echo "no specific test configured, running all"
  run_arg="gotestsum --max-fails=50 ./... -count=1 -v"
fi

TF_ACC=1 \
  TF_LOG=${log_level} \
  TEST_CONTEXT="CM" \
  PREFECT_API_URL=$(op read "${vault_entry}/api-url") \
  PREFECT_API_KEY=$(op read "${vault_entry}/api-key") \
  PREFECT_CLOUD_ACCOUNT_ID=$(op read "${vault_entry}/account-id") \
  PREFECT_ACCOUNT_NAME="latest" \
  PREFECT_ACCOUNT_HANDLE="latest" \
  PREFECT_ACCOUNT_LINK="https://github.com/PrefectHQ/terraform-provider-prefect" \
  ${run_arg}
