---
name: Acceptance Tests - OSS

"on":
  pull_request:
    branches:
      - main
    paths:
      - go.mod
      - go.sum
      - "**/*.go"
      - .github/workflows/acceptance-tests-oss.yaml

permissions: {}

jobs:
  acceptance_tests:
    permissions:
      contents: read
    name: Acceptance Tests - OSS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install tool dependencies
        uses: jdx/mise-action@v2
        with:
          install_args: go gotestsum terraform

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Prefect OSS
        run: docker compose up -d

      - name: Run acceptance tests - OSS
        run: make testacc-oss
