---
name: Acceptance Tests - OSS

"on":
  pull_request:
    branches:
      - main
    paths:
      - go.mod
      - go.sum
      - "**/*.go"
      - .github/workflows/acceptance-tests-oss.yaml

permissions: {}

jobs:
  acceptance_tests:
    permissions:
      contents: read
    name: Acceptance Tests - OSS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      # This action installs go and caches downloaded modules, so we favor
      # this over using the `mise-action` to install Go.
      - name: Set up Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Install tool dependencies
        uses: jdx/mise-action@v3
        with:
          install_args: gotestsum terraform

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Prefect OSS
        run: docker compose up -d

      - name: Run acceptance tests - OSS
        run: mise run testacc-oss
