---
  name: Labeler

  on:
    pull_request_target:
      branches:
        - main

  permissions: {}

  jobs:
    label:
      environment: Docs
      runs-on: ubuntu-latest
      permissions:
        contents: read
        pull-requests: write
      steps:
        - uses: actions/labeler@v6
          with:
            repo-token: "${{ github.token }}"
